services:
  # Redis for persistent replay protection
  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Production service (mainnet)
  randomness-prod:
    image: phantasybot/verifiable-randomness-service:v0.1.0-BETA
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
      - APP_VERSION=0.1.0-BETA
      - APP_ENVIRONMENT=production
      - PHALA_APP_ID=4379c582b5c9cf28473de17932e9d62b4eb15995
      - PAYMENT_WALLET=${PAYMENT_WALLET:-3Qudd5FG8foyFnbKxwfkDktnuushG7CDHBMSNk9owAjx}
      - PAYMENT_WALLET_BASE=${PAYMENT_WALLET_BASE:-}
      - HELIUS_RPC_URL=${HELIUS_RPC_URL:-}
      - WHITELIST=${WHITELIST:-api.mysterygift.fun,vault.mysterygift.fun,agent.mysterygift.fun,tcg.mysterygift.fun,rng.mysterygift.fun,localhost}
      - API_KEYS=${API_KEYS:-}
      - X402_FACILITATOR_URL=${X402_FACILITATOR_URL:-https://facilitator.payai.network}
      - X402_API_KEY=${X402_API_KEY:-}
      - SUPPORTED_NETWORKS=${SUPPORTED_NETWORKS:-solana,base}
      - ARWEAVE_ENABLED=${ARWEAVE_ENABLED:-true}
      - PHALA_CLUSTER=${PHALA_CLUSTER:-prod9}
      - REDIS_URL=redis://redis:6379
    volumes:
      - /var/run/dstack.sock:/var/run/dstack.sock
    depends_on:
      redis:
        condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Development service (devnet)
  randomness-dev:
    image: phantasybot/verifiable-randomness-service:v0.1.0-BETA
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - NODE_ENV=development
      - APP_VERSION=0.1.0-BETA
      - APP_ENVIRONMENT=development
      - PHALA_APP_ID=${PHALA_APP_ID_DEV:-}
      - PAYMENT_WALLET=${PAYMENT_WALLET_DEV:-}
      - PAYMENT_WALLET_BASE=${PAYMENT_WALLET_BASE_DEV:-}
      - HELIUS_RPC_URL=${HELIUS_RPC_URL_DEV:-}
      - WHITELIST=${WHITELIST_DEV:-api-dev.mysterygift.fun,vault-dev.mysterygift.fun,agent-dev.mysterygift.fun,rng-dev.mysterygift.fun,localhost}
      - API_KEYS=${API_KEYS:-}
      - X402_FACILITATOR_URL=${X402_FACILITATOR_URL:-https://facilitator.payai.network}
      - X402_API_KEY=${X402_API_KEY:-}
      - SUPPORTED_NETWORKS=${SUPPORTED_NETWORKS:-solana,base}
      - ARWEAVE_ENABLED=${ARWEAVE_ENABLED:-true}
      - PHALA_CLUSTER=${PHALA_CLUSTER:-prod9}
      - REDIS_URL=redis://redis:6379
    volumes:
      - /var/run/dstack.sock:/var/run/dstack.sock
    depends_on:
      redis:
        condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  redis-data:
