services:
  dstack-ingress-prod:
    image: dstacktee/dstack-ingress:20250924@sha256:40429d78060ef3066b5f93676bf3ba7c2e9ac47d4648440febfdda558aed4b32
    ports:
      - "443:443"
    environment:
      - DOMAIN=vrf.mysterygift.fun
      - TARGET_ENDPOINT=http://randomness-prod:3000
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
      - GATEWAY_DOMAIN=_.${DSTACK_GATEWAY_DOMAIN}
      - CERTBOT_EMAIL=${CERTBOT_EMAIL}
      - SET_CAA=true
      - PORT=443
    volumes:
      - /var/run/dstack.sock:/var/run/dstack.sock
      - cert-data:/etc/letsencrypt
    restart: always

  randomness-prod:
    image: phantasybot/verifiable-randomness-service:v0.1.0-BETA-v19
    environment:
      - PORT=3000
      - NODE_ENV=production
      - APP_VERSION=0.1.0-BETA
      - APP_ENVIRONMENT=production
      - PAYMENT_WALLET=3Qudd5FG8foyFnbKxwfkDktnuushG7CDHBMSNk9owAjx
      - PAYMENT_WALLET_BASE=0x2d55488AD8dd2671c2F8D08FAad75908afa461c3
      - HELIUS_RPC_URL=https://mainnet.helius-rpc.com/?api-key=a9b3f735-5075-44f3-a144-42e39e5f8827
      - BASE_RPC_URL=https://base-mainnet.g.alchemy.com/v2/bN0iupijudcLrsJrQ4QXB
      - API_KEYS=6d44c71a16450ce80e3bf8dc8a0904e59eaaa3524c8eb31a9f500e5743560b8b
      - X402_FACILITATOR_URL=https://facilitator.payai.network
      - SUPPORTED_NETWORKS=solana,base
    expose:
      - "3000"
    volumes:
      - /var/run/dstack.sock:/var/run/dstack.sock
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    depends_on:
      dstack-ingress-prod:
        condition: service_started

volumes:
  cert-data:
