services:
  dstack-ingress-dev:
    image: dstacktee/dstack-ingress:20250929@sha256:2b47b3e538df0b3e7724255b89369194c8c83a7cfba64d2faf0115ad0a586458
    ports:
      - "443:443"
    environment:
      - DOMAIN=vrf-dev.mysterygift.fun
      - TARGET_ENDPOINT=http://randomness-dev:3000
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
      - GATEWAY_DOMAIN=_.dstack-pha-prod9.phala.network
      - CERTBOT_EMAIL=${CERTBOT_EMAIL}
      - SET_CAA=true
      - PORT=443
    volumes:
      - /var/run/dstack.sock:/var/run/dstack.sock
      - cert-data:/etc/letsencrypt
    restart: always

  randomness-dev:
    image: phantasybot/vrf-service:0.1.0-BETA-v29
    environment:
      - PORT=3000
      - NODE_ENV=production
      - APP_VERSION=0.1.0-BETA
      - APP_ENVIRONMENT=development
      - PAYMENT_WALLET=3Qudd5FG8foyFnbKxwfkDktnuushG7CDHBMSNk9owAjx
      - PAYMENT_WALLET_BASE=0x2d55488AD8dd2671c2F8D08FAad75908afa461c3
      - HELIUS_RPC_URL=https://devnet.helius-rpc.com/?api-key=a9b3f735-5075-44f3-a144-42e39e5f8827
      - BASE_RPC_URL=https://base-sepolia.g.alchemy.com/v2/bN0iupijudcLrsJrQ4QXB
      - API_KEYS=6d44c71a16450ce80e3bf8dc8a0904e59eaaa3524c8eb31a9f500e5743560b8b
      - X402_FACILITATOR_URL=https://facilitator.payai.network
      - SUPPORTED_NETWORKS=solana,base
    expose:
      - "3000"
    volumes:
      - /var/run/dstack.sock:/var/run/dstack.sock
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    depends_on:
      dstack-ingress-dev:
        condition: service_started

volumes:
  cert-data:
