services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - /var/run/dstack.sock:/var/run/dstack.sock
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
